###
GET http://localhost:8080/api/invoices/48/items
Accept: application/json

###
POST http://localhost:8080/api/invoices/48/items
Content-Type: application/json

{
  "productName": " drill",
  "unitPrice": "15000",
  "quantity": 2
}
###


DELETE http://localhost:8080/api/invoices/50/items
Accept: application/json

###